Develop LSTM model for univeriate Time Series Forcasting

In [6]:
import numpy as np
from tensorflow.keras.layers import LSTM, Dense, Dropout,Flatten

In [7]:
from tensorflow.keras.models import Sequential


In [12]:
#prepraring the independent and dependent features
def prepare_data(timeseries_data, n_features):
    X,y =[],[]
    for i in range(len(timeseries_data)):
        #find the end of this pattern
        end_ix = i+n_features
        #check if we are beyond the sequenxce or not
        if end_ix>len(timeseries_data)-1:
            break
        #gather input  and output pairs of the pattern
        seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)


In [13]:
#define the input sequence
timeseries_data = [110,125,133,146,158,172,187,196,210]
#choose the number of the time
n_step=3
#split intop sample
X,y = prepare_data(timeseries_data, n_step)

In [14]:
print(X)

[[110 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]]


In [15]:
print(y)

[146 158 172 187 196 210]


In [16]:
X.shape

(6, 3)

In [17]:
#reshape from [sample, timestamps] into [sample, timestamps, features]
n_features=1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [19]:
X.shape

(6, 3, 1)

**Building the LSTM**

In [26]:
#Define the model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape = (n_step, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1))

In [27]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 3, 50)             10400     
                                                                 
 lstm_3 (LSTM)               (None, 50)                20200     
                                                                 
 dropout_1 (Dropout)         (None, 50)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 30,651
Trainable params: 30,651
Non-trainable params: 0
_________________________________________________________________


In [29]:
#opt = tf.keras.optimizers.Adam(lr = 1e-3, decay=1e-5)
model.compile(optimizer='adam',loss='mae',metrics=['accuracy'])
model.fit(X, y, epochs=300,batch_size=1, verbose=1)

Epoch 1/300
6/6 [==============================] - 3s 6ms/step - loss: 28.6964 - accuracy: 0.0000e+00
Epoch 2/300
6/6 [==============================] - 0s 8ms/step - loss: 20.7638 - accuracy: 0.0000e+00
Epoch 3/300
6/6 [==============================] - 0s 8ms/step - loss: 18.2316 - accuracy: 0.0000e+00
Epoch 4/300
6/6 [==============================] - 0s 9ms/step - loss: 12.0584 - accuracy: 0.0000e+00
Epoch 5/300
6/6 [==============================] - 0s 8ms/step - loss: 27.9020 - accuracy: 0.0000e+00
Epoch 6/300
6/6 [==============================] - 0s 7ms/step - loss: 19.1968 - accuracy: 0.0000e+00
Epoch 7/300
6/6 [==============================] - 0s 9ms/step - loss: 13.9917 - accuracy: 0.0000e+00
Epoch 8/300
6/6 [==============================] - 0s 8ms/step - loss: 18.2498 - accuracy: 0.0000e+00
Epoch 9/300
6/6 [==============================] - 0s 7ms/step - loss: 16.1329 - accuracy: 0.0000e+00
Epoch 10/300
6/6 [==============================] - 0s 7ms/step - loss: 14.1121 - 